authors:
  matt:
    name: Matthew Toms-Zuberec
    description: President
    avatar: /assets/images/avatars/matt.png

  silk:
    name: Stephen White
    description: Training Coordinator
    avatar: /assets/images/avatars/silk.png
